"""Format the final report as an HTML email draft."""

from datetime import date

from gmail_summarizer.matcher import MatchResult


def format_report(matches: list[MatchResult]) -> str:
    """Generate an HTML email body with ranked vacancy list."""
    today = date.today().isoformat()

    rows = ""
    for i, match in enumerate(matches, 1):
        v = match.vacancy
        gaps_html = ", ".join(match.gaps) if match.gaps else "None identified"
        key_matches_html = ", ".join(match.key_matches) if match.key_matches else "—"

        color = _fit_color(match.fit_percentage)

        rows += f"""\
        <tr>
            <td style="padding:12px;border-bottom:1px solid #eee;">{i}</td>
            <td style="padding:12px;border-bottom:1px solid #eee;">
                <a href="{v.url}" style="color:#1a73e8;text-decoration:none;">
                    <strong>{v.title}</strong>
                </a><br>
                <span style="color:#666;">{v.company} &middot; {v.location}</span>
            </td>
            <td style="padding:12px;border-bottom:1px solid #eee;text-align:center;">
                <span style="background:{color};color:#fff;padding:4px 10px;border-radius:12px;font-weight:bold;">
                    {match.fit_percentage}%
                </span>
            </td>
            <td style="padding:12px;border-bottom:1px solid #eee;">{match.summary}</td>
            <td style="padding:12px;border-bottom:1px solid #eee;font-size:0.9em;">
                <strong>Matches:</strong> {key_matches_html}<br>
                <strong>Gaps:</strong> {gaps_html}
            </td>
        </tr>"""

    return f"""\
<html>
<body style="font-family:Arial,sans-serif;color:#333;max-width:900px;margin:auto;">
    <h2 style="color:#1a73e8;">Job Opportunities Report — {today}</h2>
    <p>Found <strong>{len(matches)}</strong> matching vacancies, ranked by fit percentage.</p>
    <table style="width:100%;border-collapse:collapse;">
        <thead>
            <tr style="background:#f5f5f5;">
                <th style="padding:12px;text-align:left;">#</th>
                <th style="padding:12px;text-align:left;">Position</th>
                <th style="padding:12px;text-align:center;">Fit</th>
                <th style="padding:12px;text-align:left;">Summary</th>
                <th style="padding:12px;text-align:left;">Details</th>
            </tr>
        </thead>
        <tbody>
{rows}
        </tbody>
    </table>
    <p style="color:#999;font-size:0.85em;margin-top:24px;">
        Generated by AI Gmail Summarizer
    </p>
</body>
</html>"""


def _fit_color(pct: int) -> str:
    if pct >= 70:
        return "#34a853"
    if pct >= 50:
        return "#fbbc04"
    return "#ea4335"
